name = "DataAlignment"
uuid = "3872d29b-1e3f-4407-9c74-013bb17f40b5"
authors = ["Stuart Behling"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
